library(readxl)
library(sf)
library(stars)
library(gstat)
library(viridis)
library(RColorBrewer)
library(ggmap)
library(tidyverse)
library(mapview)
library(classInt)
library(metR)
library(OpenStreetMap) #comment out if no Java
library(svDialogs)
library(raster)
library(terra)
library(viridisLite)
